version: '3'

services:
  ssafum_bot_db:
    restart: always
    container_name: ssafum_bot_db
    image: postgres
    ports:
      - "5554:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: TelegramBot
    networks:
      - botfumnetwork

  ssafum_bot_backend:
    restart: always
    depends_on:
      - ssafum_bot_db
    build:
      context: ./BackEnd/
      dockerfile: Dockerfile
    container_name: ssafum_bot_backend
    networks:
      - botfumnetwork

  ssafum_bot_python:
    restart: always
    depends_on:
      - ssafum_bot_backend
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ssafum_bot_python
    volumes:
      - ./mainsession/session_main.session:/mainsession/session_main.session
      - ./botsession/session_bot.session:/botsession/session_bot.session
    environment:
      - SSAFUM_apiID=your_api_id
      - SSAFUM_apiHASH=your_api_hash
      - SSAFUM_botToken=your_bot_token
      - Backend_Host=host_url
      - SSAFUM_phone=your_group_chat_id
    networks:
      - botfumnetwork

networks:
  botfumnetwork:
    driver: bridge